---
output:
  pdf_document:
    toc: false
    latex_engine: xelatex
    fig_caption: true
    includes:
      in_header: "../Templates/Magazine-preamble.tex"
fontsize: 12pt
geometry:
- margin = 0.55in
- bindingoffset = 0mm # Set to 8 mm for printing
linestretch: 1
classoption: twoside
indent: true
---


# Editor Instructions

This document is designed to help you get up and running with getting magazine articles ready for production. If you're thinking, "What is \LaTeX\?", I have a short intro section at the end of this document!

### Author names

To insert an author name, type in the following code near the end of the article.

\begin{verbatim}
\begin{author-name}
Lewis Carroll
\end{author-name}
\end{verbatim}

The line will automatically stretch to fill the current text container. In the following example, I placed the author environment before \\end{multicols} to have it only take up one column.

\begin{redacted-text}

\begin{multicols}{3}

Lorem ipsum odor amet, consectetuer adipiscing elit. Tristique ridiculus interdum faucibus tellus maecenas accumsan mauris vulputate. Aliquam sollicitudin eros phasellus gravida cursus tortor lacus pulvinar. Penatibus dictum magnis sollicitudin dictumst malesuada fermentum porttitor.

Proin eu sem eget aliquet; semper suspendisse potenti ridiculus et. Aptent parturient aptent rhoncus malesuada condimentum. Nisi mus nostra congue varius pretium magnis; non dictum elit. Bibendum venenatis ac at magna mauris.

Torquent taciti arcu ligula vehicula mus non dignissim fermentum. Sagittis mollis orci aenean molestie curae lacinia nostra ullamcorper. Suscipit odio duis gravida habitant volutpat arcu. Auctor diam maximus in egestas curae rhoncus. Efficitur lectus gravida dolor ut cursus vehicula quam parturient! Luctus eleifend lacinia; velit placerat metus arcu orci vulputate.

Facilisis maximus dictumst arcu porttitor mus amet. Parturient potenti facilisis vestibulum varius metus praesent. Maximus massa sollicitudin vitae; et sed inceptos. Penatibus praesent volutpat sagittis semper hendrerit luctus finibus ante. Faucibus a magna nibh ut donec dis torquent. Massa non fermentum aliquam lobortis; conubia integer sit sollicitudin.

Facilisi maximus cursus fames pellentesque eu potenti. Imperdiet morbi suscipit aliquam suscipit maecenas per eget ut finibus. Blandit lacinia felis senectus ullamcorper praesent mollis fringilla. Suspendisse nostra ipsum iaculis conubia magna leo eget blandit. Fermentum cubilia cubilia dis; vehicula mattis sollicitudin.

Praesent vitae iaculis sodales sagittis sociosqu amet platea etiam. Non tellus sem neque, adipiscing nam inceptos ac? Dapibus nascetur cubilia vel nunc parturient convallis arcu ultricies. Massa tellus ridiculus mattis inceptos ad ex curabitur eleifend. Gravida euismod nostra ad habitant ullamcorper in dui.

\begin{author-name}

Lewis Carroll

\end{author-name}


\end{multicols}

\end{redacted-text}


### Preamble

Some articles require some explanatory text or a disclaimer before the main content. Use the preamble environment for this.

\begin{verbatim}
\begin{preamble}

Insert disclaimer text here, an intro, etc...

\end{preamble}
\end{verbatim}


### Section Titles

In most cases, \\section{Article title} should be fine. If you have a dark background image, you may want to change the text color. Use the following code at the top of the document:

\begin{verbatim}
\section{\color{white} Alice in Wonderland}
\end{verbatim}

### Images

This template uses full-bleed background images. They must be 8.5 in x 11 in, and they can be either .PDF or .PNG files (if .PNG, try to have at least 300 DPI).



## What is \LaTeX?

\LaTeX\ is a free program used to create beautifully typeset documents like books, theses, and newsletters. It is very different than Microsoft Word. Instead of selecting text and clicking on a button to make it \textbf{bold} or \textit{italicized}, you write code like \\textit{} for italics. It seems like more work than necessary, but there are several strong advantages for using \LaTeX.

### Beautiful typography

\LaTeX\ automatically handles a lot of typesetting details including:

\begin{itemize}

\item Kerning - aesthetically pleasing spacing between letters based on their shapes
\item Ligatures - new characters for letter combinations like fi and ff, which often crash into each other in Word documents.
\item Text justification without creating white rivers of blank spots
\item Consistent styles for section headers, citations, figure captions and numbering, etc.
\item and more!

\end{itemize}

Really, only typography nerds will notice or care about these details. But professional-quality typesetting does have an overall effect on the appearance of the document.

Insert comparison image here for justification and ligatures


### No manual formatting

You don't need to manually adjust spacing, figure numbers, or page numbers.

### Uses Plaintext

Word documents often crash when they get too large or have too many images. Since \LaTeX\ uses plaintext files (.txt) and sources images externally, your document stays small and portable. Plaintext files can open on any operating system, and they aren't locked into a specific version or program. You can open decades-old .txt files and they still work. You can easily link your writing to version control software like Git.

### Handles large, complex documents well

\LaTeX makes it easy for you to manage large documents like a thesis or book because it allows for easy cross-referencing of figures, footnotes, quotes, and citations. To add a list of figures, just type \\listoffigures!

Inserting a new page or image into a lengthy document (typically a harrowing process in Word) is not  difficult in \LaTeX\ and you have a lot of control over the layout of your sections. It's easy to move things around, and \LaTeX\ will automatically re-number all your figures and footnotes.

### Mathematics

One of the best features of \LaTeX\ is its mathematical typesetting. This includes auto-aligned equations and the ability to add specialized mathematical notation.

\[
\int_a^bu\frac{d^2v}{dx^2}\,dx
=\left.u\frac{dv}{dx}\right|_a^b
-\int_a^b\frac{du}{dx}\frac{dv}{dx}\,dx.
\]

